Controllers/AuthorController.cs
using Microsoft.AspNetCore.Mvc;
using CrudTest.Models;
using CrudTest.Data;
using Microsoft.EntityFrameworkCore;
using CrudTest.Repository;

namespace CrudTest.Controllers
{
    public class AuthorController : Controller
    {

        #region ctor + jections

        IUnitOfWork db;
        public AuthorController(IUnitOfWork unitOfWork)
        {
            db = unitOfWork;
        }
        #endregion

        #region Author


        #region Add Author
        [HttpGet]
        [Authorize(Trust = "yes")]
        public IActionResult AddAuthor()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<RedirectResult> AddAuthor(AuthorModel authorModel)
        {
            await db.AuthorRepository.InsertAsync(authorModel);
            db.AuthorRepository.Save();
            return Redirect(@"~/Author/AuthorList");
        }





        #endregion


        #region Delete Author

        [HttpPost]
        [Authorize(Trust = "yes")]
        public async Task<RedirectResult> DeletAuthorOnPost(int id)
        {
            var author= await db.AuthorRepository.GetByIdAsync(id);
            await db.AuthorRepository.DeleteAsync(author);
            return Redirect(@"~/Author/AuthorList");
        }

        #endregion


        #region Author List
        [Authorize(Trust = "yes")]
        public async Task<ActionResult> AuthorList()
        {
            return View(await db.AuthorRepository.GetAllAsync());
        }
        #endregion


        #endregion

    }
}

Controllers/BookController.cs
using Microsoft.AspNetCore.Mvc;
using CrudTest.Models;
using CrudTest.Data;
using Microsoft.EntityFrameworkCore;
using CrudTest.Repository;
using System.Text.Json;
using System.Text.Json.Serialization;
using Newtonsoft.Json;

namespace CrudTest.Controllers
{
    public class BookController : Controller
    {
        #region ctor + jections
        IUnitOfWork db;
        public BookController(IUnitOfWork unitOfWork)
        {
            db = unitOfWork;
        }
        #endregion


        #region Book

        #region Insert
        [Authorize(Trust = "yes")]
        [HttpGet]
        public async Task<IActionResult> InsertBook()
        {
            return View(await db.BookRepository.InsertBookOnGet());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<RedirectResult> InsertBook(BookModel bookModel)
        {
            Random rnd = new Random();
            bookModel.Rate = rnd.Next(5);
            bookModel.Price = rnd.Next(1, 1000);
            await db.BookRepository.InsertAsync(bookModel);
            db.BookRepository.Save();


            return Redirect(@"~/Book/ReadBooks");


        }
        #endregion


        #region Read
        public IActionResult ReadBooks(int? id)
        {

            var books = db.BookRepository.ReadBooks(id);
            ViewBag.LibraryId = id;
            return View(books);
        }
        #endregion


        #region Delete
        [Authorize(Trust = "yes")]
        [HttpGet]
        public async Task<IActionResult> DeleteBooks(int id)
        {
            return View(await db.BookRepository.DeleteBookOnGet(id));
        }

        [HttpPost]
        public async Task<RedirectResult> DeleteBooksOnPost(int id)
        {
            var book =await db.BookRepository.GetByIdAsync(id);
            await db.BookRepository.DeleteAsync(book);
            return Redirect(@"~/Book/ReadBooks");
        }

        #endregion


        #region Edit


        [Authorize(Trust = "yes")]
        [HttpGet]
        public IActionResult UpdateBookOnGet(int id)
        {
            return View(db.BookRepository.UpdateBookOnGet(id));
        }

        [HttpPost]
        public RedirectResult UpdateBookOnPost(BookModel bookModel)
        {


            if (bookModel != null)
            {
                Random rnd = new Random();
                bookModel.Rate = rnd.Next(5);
                bookModel.Price = rnd.Next(1, 1000);
                db.BookRepository.Update(bookModel);
            }

            db.BookRepository.Save();


            return Redirect(@"~/Book/ReadBooks");

        }

        #endregion


        #region BookById


        [HttpGet]
        public async Task<IActionResult> BookById(int id)
        {
            var book = await db.BookRepository.GetByIdAsync(id);
            return View(book);
        }
        #endregion

        #endregion

        #region Pagination
        [HttpPost]
        public JsonResult LoadData(string sortName, int? id, string sortDirection, int pageIndx, string availableItems)
        {
            Pagination<BookAuthorViewModel> model = new Pagination<BookAuthorViewModel>();
            var books = db.BookRepository.ReadBooks(id);
            int PageSize = 10;
            model.PageIndex = pageIndx;
            int startIndex = (model.PageIndex - 1) * PageSize;

            if (availableItems == "on")
                books.RemoveAll(b => b.books.Quantity == 0);

            model.LastPage = books.Count() / 10 + 1;
            model.Data = OrderBySubject(sortName, sortDirection, startIndex, PageSize, books);

            string json = JsonConvert.SerializeObject(model, Formatting.Indented, new JsonSerializerSettings
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            });


            return new JsonResult(json);
        }

        public List<BookAuthorViewModel> OrderBySubject(string sortName, string sortDirection, int startIndex, int PageSize, List<BookAuthorViewModel> books)
        {
            List<BookAuthorViewModel> Books = new List<BookAuthorViewModel>();
            switch (sortName)
            {
                case "BookID":
                case "":
                    if (sortDirection == "ASC")
                        Books = books.OrderBy(b => b.books.Id).Skip(startIndex)
                            .Take(PageSize).ToList();
                    else
                        Books = books.OrderByDescending(b => b.books.Id).Skip(startIndex)
                            .Take(PageSize).ToList();
                    break;
                case "Name":
                    if (sortDirection == "ASC")
                        Books = books.OrderBy(b => b.books.Name).Skip(startIndex)
                            .Take(PageSize).ToList();
                    else
                        Books = books.OrderByDescending(b => b.books.Name).Skip(startIndex)
                            .Take(PageSize).ToList();
                    break;
                case "ISBN":
                    if (sortDirection == "ASC")
                        Books = books.OrderBy(b => b.books.ISBN).Skip(startIndex)
                            .Take(PageSize).ToList();
                    else
                        Books = books.OrderByDescending(b => b.books.ISBN).Skip(startIndex)
                            .Take(PageSize).ToList();
                    break;
                case "Publisher":
                    if (sortDirection == "ASC")
                        Books = books.OrderBy(b => b.books.Publisher).Skip(startIndex)
                            .Take(PageSize).ToList();
                    else
                        Books = books.OrderByDescending(b => b.books.Publisher).Skip(startIndex)
                            .Take(PageSize).ToList();
                    break;
                case "Rate":
                    if (sortDirection == "ASC")
                        Books = books.OrderBy(b => b.books.Rate).Skip(startIndex)
                            .Take(PageSize).ToList();
                    else
                        Books = books.OrderByDescending(b => b.books.Rate).Skip(startIndex)
                            .Take(PageSize).ToList();
                    break;
                case "Price":
                    if (sortDirection == "ASC")
                        Books = books.OrderBy(b => b.books.Price).Skip(startIndex)
                            .Take(PageSize).ToList();
                    else
                        Books = books.OrderByDescending(b => b.books.Price).Skip(startIndex)
                            .Take(PageSize).ToList();
                    break;
                case "AuthorName":
                    Books = books.OrderBy(b => b.author.Name).Skip(startIndex)
                            .Take(PageSize).ToList();
                    break;

            }
            return Books;
        }

        public IActionResult GetBooks(int? id)
        {

            var books = db.BookRepository.ReadBooks(id);
            return View(books);
        }
        #endregion
    }
}

Controllers/LibraryController.cs
using Microsoft.AspNetCore.Mvc;
using CrudTest.Models;
using CrudTest.Data;
using Microsoft.EntityFrameworkCore;
using CrudTest.Repository;

namespace CrudTest.Controllers
{
    public class LibraryController : Controller
    {
        #region ctor + jections

        IUnitOfWork db;
        public LibraryController(IUnitOfWork unitOfWork)
        {
            db = unitOfWork;
        }
        #endregion


        #region Library


        #region AddLibrary

        [HttpGet]
        [Authorize(Trust = "yes")]
        public async Task<IActionResult> AddLibrary()
        {
            return View(await db.LibraryRepository.InsertLibraryOnGet());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<RedirectResult> AddLibraryOnPost(LibraryModel libraryModel, int[] arrays)
        {

            await db.LibraryRepository.InsertLibraryOnPost(libraryModel, arrays);
            db.LibraryRepository.Save();
            return Redirect(@"~/Library/LibraryList");

        }



        #endregion


        #region Library List
        public async Task<IActionResult> LibraryList()
        {

            return View(await db.LibraryRepository.GetAllAsync());

        }
        #endregion


        #region Delete Library
        [HttpGet]
        [Authorize(Trust = "yes")]
        public IActionResult DeleteLibrary(int id)
        {
            return View(db.LibraryRepository.DeleteLibraryOnGet(id));
        }

        [HttpPost]
        public async Task<RedirectResult> DeleteLibraryOnPost(int id)
        {
            var library =await db.LibraryRepository.GetByIdAsync(id);
            await db.LibraryRepository.DeleteAsync(library);
            return Redirect(@"~/Library/LibraryList");
        }
        #endregion


        #region Edit Library



        [HttpGet]
        [Authorize(Trust = "yes")]
        public IActionResult UpdateLibrary(int id)
        {
            return View(db.LibraryRepository.UpdateLibraryOnGet(id));
        }

        [HttpPost]
        public RedirectResult UpdateLibraryOnPost(LibraryModel libraryModel, int[] arrays)
        {

            db.LibraryRepository.UpdateLibraryOnPost(libraryModel, arrays);
            db.LibraryRepository.Save();


            return Redirect(@"~/Library/LibraryList");

        }

        #endregion


        #endregion
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />





    @*    <link rel="stylesheet" href="~/css/StyleSheet.css" />
        <link rel="stylesheet" href="~/css//Layout.css" />*@
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CrudTest.styles.css" asp-append-version="true" />


    <link rel="stylesheet" href="~/css/fonts.css">
    <link rel="stylesheet" href="~/css/Reset.css">
    <link rel="stylesheet" href="~/css//navbar.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" />

</head>
<body>

    <header>
        <nav class="nav">
            <div class="container">
                <div class="wrapper">
                    <div class="logo">
                        <img src="~/Logo.webp" alt="" class="logo__img">
                    </div>
                    <ul class="menu">
                        <li class="menu__item">
                            <a class="menu__link" asp-area="" asp-controller="Author" asp-action="AddAuthor">Add Author</a>
                        </li>
                        <li class="menu__item">
                            <a class="menu__link" asp-area="" asp-controller="Author" asp-action="AuthorList">Author List </a>
                        </li>
                        <li class="menu__item">
                            <a class="menu__link" asp-area="" asp-controller="Book" asp-action="InsertBook">Add Book</a>
                        </li>
                        <li class="menu__item">
                            <a class="menu__link" asp-area="" asp-area="" asp-controller="Book" asp-action="ReadBooks">Book List</a>
                        </li>
                        <li class="menu__item">
                            <a class="menu__link" asp-area="" asp-controller="Library" asp-action="AddLibrary">Add Library </a>
                        </li>
                        <li class="menu__item">
                            <a class="menu__link" asp-area="" asp-controller="Library" asp-action="LibraryList">Library List </a>
                        </li>








                        <li class="menu__item">
                            <a id="a1" class="menu__link menu__link-active" asp-area="" asp-controller="Account" asp-action="LoginOnGet">Login </a>
                        </li>
                    </ul>
                    <span class="fas fa-bars nav__icon"></span>
                </div>
            </div>
        </nav>







    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
<script>
        function ReadCookie() {
                   var allcookies = document.cookie;
                   // Get all the cookies pairs in an array
                   cookiearray = allcookies.split(';');
                   var name;
                   var value;
                   // Now take key value pair out of this array
                   for(var i=0; i<cookiearray.length; i++) {
                      name = cookiearray[i].split('=')[0];
                      value = cookiearray[i].split('=')[1];
                   }
                                     if(value=="yes")
                      {
                          document.getElementById('a1').innerHTML="LogOut";
                      }
                }
                ReadCookie();

                let menu = document.querySelector(".menu");


    let icon = document.querySelector(".nav__icon");

    icon.addEventListener("click",function() {
      if (this.classList.contains("fa-bars")){
        this.classList = "fas fa-times nav__icon";
        menu.style.left = 0;
      } else {
        this.classList = "fas fa-bars nav__icon";
        menu.style.left = "-220px";
      }

    })
</script>
</html>